services:
  fileserver:
    build: ./fileserver
    container_name: fileserver
    tty: true
    hostname: fileserver
    restart: always
    networks:
      vulndock:
        ipv4_address: 172.20.30.25
  php:
    build: ./php
    container_name: employee_info
    tty: true
    hostname: employee_info
    restart: always
    networks:
      vulndock:
        ipv4_address: 172.20.30.41
  db:
    build: ./db
    container_name: web_db
    tty: true
    hostname: web_db
    restart: always
    networks:
      vulndock:
        ipv4_address: 172.20.30.42
  react:
    build: ./react
    container_name: react
    tty: true
    hostname: react
    restart: always
    networks:
      vulndock:
        ipv4_address: 172.20.30.50

networks:
  vulndock:
    name: vulndock
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.30.0/24