services:
  fileserver:
    build:
      context: ./fileserver
      dockerfile: Dockerfile
    container_name: fileserver
    tty: true
    hostname: fileserver
    restart: always
    networks:
      vulndock:
        ipv4_address: 172.20.0.25

networks:
  vulndock:
    name: vulndock
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24